### ISSUE TITLE
Problem with images loaded from external sources without content-type header

### ISSUE THREAD

**Issue by Hrishikesh-K** [netlify/netlify-ipx#2]
Hi team,

As discussed in our weekly sync regarding the ticket (internal only): https://netlify.zendesk.com/agent/tickets/75571, WEBP images requested from an external API that do not return a valid content-type header fail to load. The Next.js plugin makes a request to the IPX function and that returns a 502 with the error:

```
{"errorType":"TypeError","errorMessage":"Cannot read property 'startsWith' of null","trace":["TypeError: Cannot read property 'startsWith' of null","    at loadSourceImage (/var/task/node_modules/@netlify/ipx/dist/http.js:111:46)","    at async handler (/var/task/node_modules/@netlify/ipx/dist/index.js:56:54)"]}
```

This issue was last reproducible with Plugin v4 RC1.

**Comment by aureliendebord** [comment]
Hello,
Upgrading to the last version of next + last version of the plugin, the problem is still here.
Is here any other updates or fix to deploy?
