### ISSUE TITLE
Check if tmp has space, and clear it up if there is no space

### ISSUE THREAD

**Issue by sarahetter** [netlify/netlify-ipx#45]
Related: https://github.com/netlify/netlify-plugin-nextjs/issues/1422

If a user has a large number of images, the cache can get too full (over 512MB). We need to check if it's full if we're wanting to write to it, and clear it out if so.

Once this is closed, we should also close the related issue linked above in the next plugin repo.

**Comment by ascorbic** [comment]
This could be something we could use: https://github.com/yetzt/node-lru-files

**Comment by ceboop** [comment]
hi @pieh ! 

i am running to this issue on a project and noticed that you self-assigned the issue. do you have a sense of when you might have a possible fix? if i'm hoping to ship this project by may 7, do you recommend using @netlify/ipx@1.4.0 released with changes from https://github.com/netlify/netlify-ipx/pull/136 ? or do you think you might have a patch around then?

thank you so so much

**Comment by pieh** [comment]
Hi @ceboop. I would definitely recommend using `@netlify/ipx@1.4.0` is you were hitting disk space issues before. I will actually close this ticket as my changes don't exactly do what this ticket recommended but it still address same issue. If you will hit disk space issues with `@netlify/ipx@1.4.0`, please open a new ticket and then we will have another look (I could no longer reproduce disk space issues with my changes but it doesn't mean they won't happen)
